### ISSUE TITLE
The type for property has been changed from UInt64 to UInt64

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#103]
I have a database class with a `DateTime` property called `CreateDate`. The table and column schema was created with StarDump using the Starcounter.Core facilities. The column was created with datatype of 'ulong'.

On database startup time I receive the following message, which does not make any sense.

```
A database type declared a persistent field that did not match the signature of the attribute in the core schema. The type for property/field 'CreateDate' in class 'Surveys.webpages_Membership' has been changed from 'UInt64' to 'UInt64'.
```

cc @per-samuelsson, @k-rus, @linkdata

**Comment by miyconst** [comment]
To be more clear, this `sccoredb.STAR_TYPE_ULONG` constant is used when `DateTime` columns created.

```
Starcounter-RC-2.3.1.6410 (May 6, 2017 1:02:27 AM)
```

**Comment by linkdata** [comment]
Yeah, that seems weird. Where is the message coming from?

**Comment by miyconst** [comment]
The error message is copied from Visual Studio, when I tried to start up an app, I will check Starcounter logs as soon as I finish with meetings.

**Comment by miyconst** [comment]
Here is the full exception stack trace:

```
"Starcounter.DbException: ScErrFieldSignatureDeviation (SCERR4128): A database type declared a persistent field that did not match the signature of the attribute in the core schema. The type for property/field 'CreateDate' in class 'Surveys.webpages_Membership' has been changed from 'UInt64' to 'UInt64'.
Version: 2.3.1.6410.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4128.
   at Starcounter.Binding.TableUpgrade.VerifyColumnType(ColumnDef oldCol, ColumnDef newCol) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 130
   at Starcounter.Binding.TableUpgrade.Eval() in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 78
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 456
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 354
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-5176\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 89
ErrorCode=4128
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4128
"
```

**Comment by linkdata** [comment]
I've no idea what's going on there.

**Comment by chrhol** [comment]
It's the verification in managed code that runs when database classes are loaded that throws this.

The particular code is this (`TableUpgrade.cs`, lines 128-139):

```csharp
private void VerifyColumnType(ColumnDef oldCol, ColumnDef newCol) {
    if (newCol.Type != oldCol.Type || newCol.IsNullable != oldCol.IsNullable) {
        throw ErrorCode.ToException(Error.SCERRFIELDSIGNATUREDEVIATION,
                     string.Format("The type for property/field '{0}' in class '{1}' has been changed from '{2}' to '{3}'.",
                     newCol.Name, 
                     newTableDef_.Name,
                     BindingHelper.ConvertScTypeCodeToDbTypeCode(oldCol.Type),
                     BindingHelper.ConvertScTypeCodeToDbTypeCode(newCol.Type)
          ));
     }
 }
```
`newCol` is from the class being loaded, while `oldCol` comes from the existing schema.

So it looks like either there is a mismatch for the typecode (byte) for the column being compared or it have changed from/to nullable, and the errormessage does not specify it.

**Comment by linkdata** [comment]
The nullability condition must be present in the message there, so that's a separate issue that needs to be fixed.

@miyconst can you check the nullability of the field in question in the databases and class definitions? It seems likely that it differing would be the cause of the error.

**Comment by miyconst** [comment]
Thanks @chrhol for the investigation, it looks like the case. I will double check a bit later.

**Comment by miyconst** [comment]
@chrhol thanks for fixing the error message. This was the reason in my case, closing.
