### ISSUE TITLE
DELETE FROM fails with The transaction was aborted because of an invalid object access

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#110]
I have the following code:

```cs
Db.Transact(() =>
{
    Db.SlowSQL("DELETE FROM Country");
});
```

And it fails with the following exception:

```
"Starcounter.TransactionAbortedException: ScErrInvalidObjectAccessAbort (SCERR8006): The transaction was aborted because of an invalid object access.
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8006.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Mock\Db.cs:line 132
   at Starcounter.Db.SlowSQL(String query, Object[] values) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Mock\Db.cs:line 104
   at SyncEngine.Configurator.DemoPage.<Handle>b__10_0() in D:\GitHub\Starcounter\SyncEngine\src\SyncEngine.Configurator\ViewModels\DemoPage.json.cs:line 142
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Db.cs:line 283
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Db.cs:line 340
   at SyncEngine.Configurator.DemoPage.Handle(DeleteEverythingClick action) in D:\GitHub\Starcounter\SyncEngine\src\SyncEngine.Configurator\ViewModels\DemoPage.json.cs:line 138
   at SyncEngine.Configurator.DemoPage.JsonByExample.Schema.<>c.<.ctor>b__0_16(Json pup, Input`1 input)
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 267
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 289
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 149
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 537
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 445
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
ErrorCode=8006
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8006
"
```

What could be the reason for this?

cc @k-rus

**Comment by miyconst** [comment]
The reason for this issue was an error inside commit hooks. It's bad that it is not shown in the stack trace or in the error message, but closing the question for now.
