### ISSUE TITLE
Db.TransactAsync loses context on async operations

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#125]
If TransactAsync is used together with async operations that trigger an async continuation.
Starcounter seems to lose the current context.

Code to reproduce:
```csharp
        await Db.TransactAsync(async  () =>
        {
            await Task.Delay(1000); //cause an async continuation
            new Spender
            {
                FirstName = "John",
                LastName = "Doe"
            };
        });
```

Two things here:

1) I would guess the current context is stored in a thread static var right now?
This should be replaced with an `AsyncLocal` or earlier .NET `CallContext.LogicalSetData` to allow context to flow between async operaitons.

2) The TransactAsync consumes an Action, that is, a void func. this seems odd since async void is an antipattern

Am I holding it wrong or are these observations correct?

Error log when switching thread inside `TransactAsync`
```
System.Exception: ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.
Version: 2.3.1.6481.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1004.
   at Starcounter.ThreadData.GetContextHandleExcept() in C:\TeamCity\TeamCity10\buildAgent\work\sc-5444\Level1\src\Starcounter\Internal\ThreadData.cs:line 70
   at Starcounter.SqlProcessor.SqlProcessor.GetSetSpecifier(UInt16 layoutId) in C:\TeamCity\TeamCity10\buildAgent\work\sc-5444\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 232
   at Starcounter.Internal.DbState.Insert(UInt16 tableId, UInt64& oid, UInt64& address) in C:\TeamCity\TeamCity10\buildAgent\work\sc-5444\Level1\src\Starcounter\Internal\DbState.cs:line 114
   at Person..ctor(UInt16 tableId, TypeBinding typeBinding, Initialized dummy)
   at Person..ctor(UInt16 tableId, TypeBinding typeBinding, Uninitialized dummy)
   at Spender..ctor(UInt16 tableId, TypeBinding typeBinding, Uninitialized dummy)
   at Spender..ctor()
   at Program.<>c.<<SetupData>b__1_0>d.MoveNext() in C:\Users\
ojo01\documents\visual studio 2017\Projects\StarcounterApplication1\StarcounterApplication1\Program.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1004
```

**Comment by miyconst** [comment]
cc @bigwad, @alemoi

**Comment by bigwad** [comment]
Unfortunately, it's known limitation that Starcounter doesn't support asynchronous transaction delegates. We're moving in that direction (https://github.com/Starcounter/level1/issues/2796) and Db.TransactAsync will accept `Func<Task>` once we are there.

What I can suggest now:
Try to avoid blocking IO inside a transaction delegate. Kind of obvious, but still... Consider preparing data in advance or splitting workload into several transactions.
Or if blocking IO is absolutely necessary then give a try to Starcounter internal scheduling and just make synchronous IO call. Starcounter scheduler is able to detect blocking call and launch additional processing thread.


Probably, you're wondering why there is TransactAsync then if Starcounter doesn't support async delegates? Its only purpose is to allow user code to run in parallel with a transaction being flushed to a disk.

**Comment by rogeralsing** [comment]
Got it, just trying things out here. closing
