### ISSUE TITLE
Improve user experience for various multihost related management ops

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Home#132]
Use case 1 (done)
-----------
  * Shared host is running
  * App that host itself start
  
Now:

```  
Unhandled Exception: System.Exception: ScErrAppAlreadyStarted (SCERR2001): A Starcounter process with the specified name is already started.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2001.
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.AssureNoOtherProcessWithTheSameName(IHostConfiguration c)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider)
   at Starcounter.Hosting.SelfHostedCodeHost.RunHost(RuntimeHost host)
   at Starcounter.Hosting.SelfHostedCodeHost.Run(Action applicationMainLoop)
   at SelfHostedApp.Program.Main(String[] args) in C:\Users\Per\proj\StarcounterApplication48\SelfHostedApp\Program.cs:line 14
```

Decent UX: Unable to load database "default" since it's already loaded in another host process.

Done as: 

> Starcounter.Hosting.RuntimeHosts.RuntimeHost.AssureNoOtherProcessWithTheSameName(IHostConfiguration c)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider)
   at Starcounter.Hosting.SelfHostedCodeHost.RunHost(RuntimeHost host)
   at Starcounter.Hosting.SelfHostedCodeHost.Start()
   at StarcounterApplication48.Test.Class1.TestCreatingFooAndFriends() in C:\Users\Per\proj\StarcounterApplication48\StarcounterApplication48.Test\Class1.cs:line 18
Result Message:	
System.NotImplementedException : ScErrNotImplemented (SCERR1027): The method, operation or feature is not implemented. Loading databases in multiple processes is not yet supported. Database DEFAULT is already loaded. Use `staradmin list db` to see in what process.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1027.

Use case 2 (Done)
-----------
  * App that host itself is running
  * App want to start in the shared host start, i.e. star app.cs

  Now: terrible error from logs, not usable.

  Desired: explained that we cant run app in shared host because another host already
  have the database loaded (hint on staradmin list db / list apps?)

Use case 3 (Done)
-----------
  * Shared host is running
  * Unit test that host app start

Use case 4 (Done)
-----------
  * App that host itself is running
  * Another app that host itself start

Resolved using (same as use case 1):

> System.NotImplementedException : ScErrNotImplemented (SCERR1027): The method, operation or feature is not implemented. Loading databases in multiple processes is not yet supported. Database DEFAULT is already loaded. Use `staradmin list db` to see in what process.

Use case 5
-----------
  * Starting an app that use AppHostBuilder hosting API in the shared host.
  What should happen? How to craft a startup to support both?

Use case 6 (Done)
------------
  * App that host itself is running
  * User doing `staradmin stop db | host | app`

Tracked explicitly in https://github.com/Starcounter/Home/issues/131

**Comment by per-samuelsson** [comment]
>Use case 3 (Done)
>-----------
>  * Shared host is running
>  * Unit test that host app start

I'm reusing experience from when a self-hosted app starts, and shared host is running. I think its an acceptable user experience, and I can't find any better at this moment.

**Comment by per-samuelsson** [comment]
>Use case 2 (Done)
>-----------
>  * App that host itself is running
>  * App want to start in the shared host start, i.e. star app.cs

>  Now: terrible error from logs, not usable.

>  Desired: explained that we cant run app in shared host because another host already
>  have the database loaded (hint on staradmin list db / list apps?)

Here's the new experience at this point:

```
star app.cs
```

> ScErrNotSupported (SCERR1005): The requested operation is not supported on the specific object. Starting app in default failed. Database default is already hosted in process 15352 and that host support only a single application.

Didn't introduce any specific new error code here either, since this case *will* eventually be supported (if we could just start the shared host while another host/app is running). We might want to review that, depending on how far away support for that is.

**Comment by per-samuelsson** [comment]
>Use case 6 (Done)
>------------
>  * App that host itself is running
>  * User doing `staradmin stop db | host | app`

> Tracked explicitly in https://github.com/Starcounter/Home/issues/131

Done. See #131.

**Comment by per-samuelsson** [comment]
> Use case 5
> -----------
> * Starting an app that use AppHostBuilder hosting API in the shared host.
> What should happen? How to craft a startup to support both?

Above is the last piece left from OP, and I've started working on that in a specific issue: #146. Hence, I'm closing this one as done.
