### ISSUE TITLE
Socket connection lost when updating large collection of data from Polymer 

### ISSUE THREAD

**Issue by nazmuladfenix** [Starcounter/Home#202]
I am updating large collection on single event. Then its lost the socket connection and trying to reconnect. 

In starcounter log I have found this error log 

> System.Exception: Unknown WebSocket frame type: 0
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 716
HResult=-2146233088

and another is 

> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[9].path', line 1, position 992.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 421
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
LineNumber=1
LinePosition=992
Path=[9].path
HResult=-2146233088

How can I solve this problem ?

**Comment by Mackiovello** [comment]
It should be fixed according to https://github.com/Starcounter/Home/issues/187.  @alemoi could you take a look?

**Comment by nazmuladfenix** [comment]
Thanks :) Got it

**Comment by alemoi** [comment]
My first question will be what version of SC do you use. Since this problem should already be fixed. Thanks!

**Comment by Mackiovello** [comment]
It seems like this was solved? I'm closing, if you still can't make it work @nazmuladfenix, please reopen

**Comment by nazmuladfenix** [comment]
Starcounter version currently using: Starcounter-RC-2.3.0.5971
