### ISSUE TITLE
ArgumentOutOfRangeException when starting app with star from bin/Debug directory

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#218]
Steps to reproduce:
```bash
git clone https://github.com/StarcounterApps/HelloWorld.git
cd HelloWorld
.\build.bat
star .\src\HelloWorld\bin\Debug\HelloWorld
```

If you go to `localhost:8080/HelloWorld`, you will see this:
![capture1](https://user-images.githubusercontent.com/19392292/29820540-155a6d7e-8cc5-11e7-97de-579cc993a614.PNG)

Then, run:
```bash
cd .\src\HelloWorld\bin\Debug
star HelloWorld
```

On `localhost:8080/HelloWorld` you now see this:
```txt
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Can not find referenced Html file: "/HelloWorld/PersonJson.html"
   at Starcounter.HtmlFromJsonProvider.ProvideFromFilePath[T](String filePath) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 58
   at Starcounter.HtmlFromJsonProvider.Invoke(MimeProviderContext context, Action next) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 52
   at Starcounter.MimeProviderMap.InvokeAll(MimeType type, Request request, IResource resource) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter\Middleware\MimeProviderMap.cs:line 126
   at Starcounter.Internal.ResourceMimeConverter.TryConvert(Request request, IResource resource, String mimeTypeStr, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 56
   at Starcounter.Internal.ResourceMimeConverter.Convert(Request request, Response response, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 46
   at Starcounter.Response.ConvertResource(Request req) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Internal\Http\Response.cs:line 765
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Internal\Http\Response.cs:line 821
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-7450\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 819
ParamName=Can not find referenced Html file: "/HelloWorld/PersonJson.html"
HResult=-2146233086

More information about this error may be available in the server error log.
```

Is this a bug, am I doing something wrong, or is this how it's supposed to work? Anyway, the error is confusing.      

I've also tried with another app.

Again, this is a low-prio issue that should be dealt with together with other CLI improvements.

CC @ubbeK

**Comment by ubbeK** [comment]
I think you have to set the `--resourcedir` argument, to the root of your `wwwroot` folder.

**Comment by Mackiovello** [comment]
> I think you have to set the --resourcedir argument, to the root of your wwwroot folder.

You're right. I messed up. Closing
