### ISSUE TITLE
Starcounter.TransactionAbortedException: ScErrMemoryLimitReachedAbort (SCERR8036): The transaction was aborted because limit reached on limited memory resource.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#248]
My table contains 107729703 records, when I try to clean the table I get following exception

```cs
Starcounter.TransactionAbortedException: ScErrMemoryLimitReachedAbort (SCERR8036): The transaction was aborted because limit reached on limited memory resource.
Version: 2.3.1.7166.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8036.
   at Starcounter.Internal.SqlRestHandler.<>c.<Register>b__0_1(Request req) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 60
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 773
ErrorCode=8036
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8036
```

**Comment by miyconst** [comment]
>... when I try to clean the table I get following exception.

In this case "cleaning" means executing `DELETE FROM X` statement, am I right?

**Comment by atifwaqar** [comment]
> In this case "cleaning" means executing DELETE FROM X statement, am I right?

Yes that's right

**Comment by bigwad** [comment]
The transaction has exceeded the size limit: https://docs.starcounter.io/guides/working-with-starcounter/kernel-q-and-a/

**Comment by Mackiovello** [comment]
This has been documented here: https://docs.starcounter.io/guides/database/data-manipulation#scerrmemorylimitreachedabort-(scerr8036)

Closing as answered.

**Comment by atifwaqar** [comment]
Thanks guys.
