### ISSUE TITLE
Starcounter.XSON.JsonPatchException: Unknown property in path.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#255]
SC Version 2.3.1.7166 

It looks like this exception is caused when we do some operation in our BackOffice (an admin page with Json Code behind created in SC )
```
Starcounter.XSON.JsonPatchException: Unknown property in path. Patch: '{"op":"replace","path":"/WebsiteProvider_0/Sections/Main/WebsiteProvider_0/Content/AdFenix_0/CurrentPage/AdFenix_0/SelectedPublicationOwnerID$","value":"oY7"}'. Property: 'CurrentPage'. Viewmodel versions: {client (_ver#c$): 1, clients serverversion: 0, server (_ver#s): 4}.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 172
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 552
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 481
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 379
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__8_0(Session session, Request request) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 113
Patch={"op":"replace","path":"/WebsiteProvider_0/Sections/Main/WebsiteProvider_0/Content/AdFenix_0/CurrentPage/AdFenix_0/SelectedPublicationOwnerID$","value":"oY7"}
CurrentProperty=CurrentPage
Severity=1
HResult=-2146233088
```

**Comment by atifwaqar** [comment]
A similar exception 

```
Starcounter.XSON.JsonPatchException: Unknown property in path. Patch: '{"op":"replace","path":"/Administrator_0/Databases/0/_queryState/sqlQuery","value":"a"}'. Property: '_queryState'.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 172
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 552
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 481
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 379
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterFullModelApi>b__6_2(String data, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 143
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
Patch={"op":"replace","path":"/Administrator_0/Databases/0/_queryState/sqlQuery","value":"a"}
CurrentProperty=_queryState
Severity=1
HResult=-2146233088
```

**Comment by chrhol** [comment]
The second stacktrace points to the Administrator, so that one is not connected to the first one. I created an issue for the administrator one (#258)

**Comment by miyconst** [comment]
@atifwaqar I am closing this issue, since no more information was provided. Please reopen if it is still happening.
