### ISSUE TITLE
Get an error when update the develop package [SCERR11015]

### ISSUE THREAD

**Issue by dttrung** [Starcounter/Home#268]
Hi everyone, 
When I update the new version I have got a error message.

```
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at IWshRuntimeLibrary.IWshShortcut.Save()
   at Starcounter.InstallerEngine.Utilities.CreateShortcut(String pathToOrigin, String pathToLnk, String commandArgs, String workingDir, String description, String iconPath)
   at Starcounter.InstallerEngine.CPersonalServer.CreatePersonalServerShortcuts()
   at Starcounter.InstallerEngine.CPersonalServer.Install()
   at Starcounter.InstallerEngine.InstallerMain.InstallAllComponents()
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback)
```

With link refer to [https://docs.starcounter.io/?q=SCERR11015](https://docs.starcounter.io/?q=SCERR11015)

Could you please help me?

Thanks.

**Comment by per-samuelsson** [comment]
cc @alemoi

**Comment by alemoi** [comment]
Please also provide information about what operating system you are using. CC @ubbeK

**Comment by dttrung** [comment]
Thank you for your replying.
Could you please the video below to get information?

[https://www.youtube.com/watch?v=OzGjSSRN9aQ](https://www.youtube.com/watch?v=OzGjSSRN9aQ)


```
I have installed the old version, after download new version, and upgrade, get error, that make Starcounter in my local is broken, don't work anymore.

Error occurred during installation:

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at IWshRuntimeLibrary.IWshShortcut.Save()
   at Starcounter.InstallerEngine.Utilities.CreateShortcut(String pathToOrigin, String pathToLnk, String commandArgs, String workingDir, String description, String iconPath)
   at Starcounter.InstallerEngine.CPersonalServer.CreatePersonalServerShortcuts()
   at Starcounter.InstallerEngine.CPersonalServer.Install()
   at Starcounter.InstallerEngine.InstallerMain.InstallAllComponents()
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback)

Running rollback...

-----------------------------------

Error occurred during rollback:
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at IWshRuntimeLibrary.IWshShortcut.Save()
   at Starcounter.InstallerEngine.Utilities.CreateShortcut(String pathToOrigin, String pathToLnk, String commandArgs, String workingDir, String description, String iconPath)
   at Starcounter.InstallerEngine.CPersonalServer.CreatePersonalServerShortcuts()
   at Starcounter.InstallerEngine.CPersonalServer.Install()
   at Starcounter.InstallerEngine.InstallerMain.InstallAllComponents()
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback)

Do you want to completely cleanup your system from Starcounter?

---------------------------------

ScErrInstallerAborted (SCERR11015): Installation process has been aborted. Starcounter rollback has failed. User proceeded with clean up. Clean up finished.
Version: 0.0.0.
Help page: https://docs.starcounter.io/?q=SCERR11015.
```

**Comment by ubbeK** [comment]
@dttrung Thanks for the video.

I looks like you are using Windows 10, but could you please confirm that?

For me, it looks like you are not local admin on your computer. The `User Account Control` overlay didn't show on your video when starting the installer. Could you please right click on the installer file and choose `Run as Administrator`.

On a side note, is there a reason why you are using Starcounter `2.4`? I would recommend you to use the latest Release Candidate version, `2.3.1.X` since it's API will not change until release but `2.4` may.

**Comment by miyconst** [comment]
Archiving as there is no response from @dttrung.
