### ISSUE TITLE
Unable to start DB, Receiving ScErrDataManagerDisconnected (SCERR4296) 

### ISSUE THREAD

**Issue by Razkan** [Starcounter/Home#277]
Besides restarting the computer, I have uninstalled and reinstalled SC.

Here are the following error messages copied from the log.

```
ScErrServerCommandFailed (SCERR10011): The operation "Starting database localdev." failed.
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.
```

```
Starcounter.DbException: ScErrDataManagerDisconnected (SCERR4296): Communication with data manager failed because client was disconnected by data manager. Version: 2.3.0.6350. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4296. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 333
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 73
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4296
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4296
```

```
Starcounter.DbException: ScErrDataManagerDisconnected (SCERR4296): Communication with data manager failed because client was disconnected by data manager.
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4296.
   at StarcounterInternal.Bootstrap.Control.ConnectDatabase(Guid db_uuid, UInt32 schedulerCount, UInt64 hlogs) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Bootstrap\Control.cs:line 530
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Bootstrap\Control.cs:line 224
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
ErrorCode=4296
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4296
```

**Comment by miyconst** [comment]
@Razkan thank you for reporting the issue. Can you please clarify:

- Under which version of Starcounter the database was created?
- Did you apply database schema changes?
- Did you upgrade/downgrade Starcounter?
- Are you trying to start the database itself or some apps inside it?

**Comment by Razkan** [comment]
Hi @miyconst,

1. I am fairly certain it was created under: 2.3.0.6350 (with 100% accuracy it was 2.3.0.x)
2. Yes and no. The change was done about a week ago, but the database has been working for that whole time until yesterday.
3 .I have downgraded/upgraded Starcounter between 2.3.0.6350, 2.3.1.7280 and 2.3.1.7294. (Mostly 2.3.0.6350 -> 2.3.1.7294 and back)
4. Both. I have tried the following: staradmin, the web UI & stardump all resulting with the same error message.

**Comment by miyconst** [comment]
@Razkan thank you for the info.

Unfortunately migration from `2.3.1` to `2.3.0` is not possible. Could you please try to install latest `2.3.1.x` and check if you database starts.

Do you have any confidential data inside the database? If no, could you provide us the physical database files?

**Comment by Razkan** [comment]
The Db has been transfered to @miyconst. Think this issue can be closed for now.
