### ISSUE TITLE
ScErrTransactionClosed (SCERR4260) on redirect

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Home#287]
I will use [Barcodes](https://github.com/StarcounterApps/Barcodes) as an example, but the same problem can be reproduce with other apps.

1. Get https://github.com/StarcounterApps/Barcodes/commit/f4a891cae6f928fda77f34be353341e2cb07206b (we won't use the latest version on develop because we want to use the same version of Barcodes for different SC versions), build and run in
2. Get https://github.com/Starcounter/Website/commit/16beaa01bbbf241dceb1a23c48c37728d0774224 (we won't use the latest version on develop because we want to use the same version of Website for different SC versions), build and run it
3. (I don't think it is needed, but I don't want to delete my db)  Get https://github.com/Starcounter/SampleWebsiteTheme/tree/develop , build and run in.
4. Navigate to `/barcodes/barcodes/`
5. Click "Cancel"
6. Click "Add new barcode"
7. Click "Cancel"

## Expected result

Redirects to `/barcodes`

## Actual result

I get an error.

> Starcounter.DbException: ScErrTransactionClosed (SCERR4260): An operation failed because transaction has been closed.
> Version: 2.3.1.7529.
> Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4260.
>    at Starcounter.Internal.TransactionManager.VerifyTransaction(TransactionHandle handle) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\TransactionManager.cs:line 348
>    at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\TransactionManager.cs:line 548
>    at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\Transaction.cs:line 224
>    at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
>    at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
>    at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 601
>    at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 495
>    at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
>    at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__7_0(Session session, Request request) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 130
>    at lambda_method(Closure , Request , IntPtr , IntPtr )
>    at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
>    at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
>    at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
> ErrorCode=4260
> HResult=-2146233088
> HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4260

I get this error when using the RC 2.3.1.7534 or RC 2.3.1.7529, but I don't get the error for 2.3.1.7478 .

I can also reproduce this error on RC 2.3.1.7534 or RC 2.3.1.7529, but not on 2.3.1.7478 with https://github.com/Starcounter/Website/commit/9485ca9ee0bdaf282780fb57c5860199d964e24e , a commit that was made on 17 oct.

**Also, I can't reproduce this problem no matter the SC version if the only app that is running is Barcodes app.**

Update: I ran RC 2.3.1.7478 and locally replace puppet-redirect with latest version and I get the same problem. What I'm not sure is if I suppose to get this error or not.

**Comment by Mihaiii** [comment]
Closing as fixed.
