### ISSUE TITLE
ScErrorTableNotFound after running DROP COLUMN

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#321]
Steps to reproduce:

1. Create a simple application:

```cs
using System;
using Starcounter;

namespace StarcounterApplication1
{
    [Database]
    public class Person
    {
        public string Name { get; set; }
        public string IrrelevantFact { get; set; }
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() =>
            {
                new Person()
                {
                    Name = "John",
                    IrrelevantFact = "very irrelevant"
                };
            });
        }
    }
}
```

2. Run and confirm that the`Person` table has one row with two columns.

3. Delete one property, such as `IrrelevantFact`

4. Build and run. Confirm that there is still one instance of `Person` with **one** column.

5. Run `ALTER TABLE StarcounterApplication1.Person DROP COLUMN IrrelevantFact`

6. Run `SELECT * FROM StarcounterApplication1.Person`

7. Starcounter throws:

```
Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found. No table is associated with layout id 297.
Version: 2.3.1.7870.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4230.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 391
   at Starcounter.SqlProcessor.SqlProcessor.GetSetSpecifier(UInt16 layoutId) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 232
   at Starcounter.Query.Execution.FullTableScan.CreateRangeKeys() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 135
   at Starcounter.Query.Execution.FullTableScan.Clone(RowTypeBinding typeBindingClone, VariableArray varArrClone) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 710
   at Starcounter.Query.Execution.ExecutionEnumerator.CloneCached() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\Execution\Enumerators\ExecutionEnumerator.cs:line 509
   at Starcounter.Query.Sql.SqlEnumCache.GetCachedEnumerator(Int32 uniqueQueryId) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 86
   at Starcounter.QueryResultRows`1.GetExecutionEnumerator() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 111
   at Starcounter.QueryResultRows`1.GetEnumerator() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 52
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 102
ErrorCode=4230
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4230
```

If I try to start the app again, I get a bunch or errors in the log:

```
Starcounter.DbException: ScErrColumnNameNotUnique (SCERR4277): Create table failed because one or more columns shared the same name token as another column. Table StarcounterApplication1.Person: added column Name conflicts with existing column.
Version: 2.3.1.7870.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4277.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 391
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Db.cs:line 335
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Db.cs:line 446
   at Starcounter.SqlProcessor.SqlProcessor.AlterTableAddColumns(String full_table_name, STAR_COLUMN_DEFINITION_WITH_NAMES* added_columns, UInt64& new_layout_handle) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 163
   at Starcounter.Binding.TableUpgrade.Eval() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 102
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 457
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 355
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 266
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 139
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 89
ErrorCode=4277
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4277
```

```
Starcounter.DbException: ScErrColumnNameNotUnique (SCERR4277): Create table failed because one or more columns shared the same name token as another column. Table StarcounterApplication1.Person: added column Name conflicts with existing column. Version: 2.3.1.7870. Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4277. 
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4277
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4277
```

```
ScErrServerCommandFailed (SCERR10011): The operation "Starting StarcounterApplication1 in default" failed. Version: 2.3.1.7870. Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR10011.
--
```

```
System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost "default.
Version: 2.3.1.7870.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR2047.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 64
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 139
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter.Bootstrap\Control.cs:line 216
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR2047
```

```
System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost "default. Version: 2.3.1.7870. Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR2047.     at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 333    at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 462    at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-11226\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300 HResult=-2146233088 HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR2047
--
```

```
ScErrServerCommandFailed (SCERR10011): The operation "Attempting to restart code host for default" failed.
Version: 2.3.1.7870.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR10011.
```

Am I doing something wrong or is this a bug? I don't understand why the table can't be found after I've dropped a column.

**Comment by miyconst** [comment]
cc @per-samuelsson

**Comment by per-samuelsson** [comment]
> cc @per-samuelsson

Think this is more for @k-rus and the guys, but I'll do a preliminary test with same use case to see what i get.

**Comment by per-samuelsson** [comment]
> ...  but I'll do a preliminary test with same use case to see what i get.

Confirm I get the same experience, with a minor comment: there are *two* instances after the restart (which is expected, since a new is created on each restart).

Tried thinking about what I did differently yesterday and remembered that I **stopped** the app before I executed any table alternations. So my sequence was:

1. Start application. Verify data is there.
2. Run `staradmin stop app StarcounterApplication1`
3. Removed property from class.
4. Started app. Verified again data is there (minus removed property/column).
5. Executed ALTER TABLE.

In your case, you are actually altering the table while the application is running (but the column is no longer mapped, because you have removed it from the class). Maybe that is not supported? 

I'll let @k-rus have his say on that.

**Comment by k-rus** [comment]
I cannot tell now what is supported and what is supposed to work as I don't remember. It was implemented half year ago.
Actually altering table cannot work correctly from Level1, since Level1 keeps using obsolete layout handle. I guess the metalayer controls only that the column to drop is not used by any application. This will explain the undefined behaviour in the OP.

**Comment by k-rus** [comment]
This was a bug in the metalayer. It was discussed and fixed in internal issue https://github.com/Starcounter/level1/issues/4375
