### ISSUE TITLE
Upgrade  from 2.4.0.4182 to 2.4.0.4210 gives error.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#342]
If new DB created it is working.

```
System.Exception: ScErrMetaschemaVersionMismatch (SCERR15010): The version of the metaschema in the database does not match the metaschema version in Starcounter's binary. This version of Starcounter has metaschema version 4, while the database has version 5.
Version: 2.4.0.4210.
Help page: https://docs.starcounter.io/?q=SCERR15010.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.QueryProcessor\interop\SqlProcessor.cs:line 272
   at Starcounter.SqlProcessor.SqlProcessor4MetaData.PopulateRuntimeMetadata() in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 66
   at Starcounter.Hosting.StarcounterPackage.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.Hosting\Hosting\StarcounterPackage.cs:line 44
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 269
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 137
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 51
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-12209\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 90
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR15010
```

**Comment by k-rus** [comment]
Thank you for reporting the issue!
The error message is misleading, since new version of Starcounter (2.4.0.4210) has metaschema version 5, while the database was created with metaschema version 4. This error means that the database cannot be started with new version of Starcounter, thus it needs to be unloaded using the old version of Starcounter and then loaded after the installation of newer version of Starcounter.

Actually, I think in this case new version of Starcounter should be able to load the database. @alexanderstc Can you confirm?
So we need to fix the check that it only prevents loading the database and returning the message when the metaschema is incompatible.

**Comment by alexanderstc** [comment]
> I think in this case new version of Starcounter should be able to load the database

I think so too.

**Comment by alexanderstc** [comment]
@SenerDemiral

**Comment by alexanderstc** [comment]
@SenerDemiral 
you move from 2.4.0.4182 to 2.4.0.4210.
Well, 2.4.0.4182 is a private build which has metaschema version of 5,
wgile 2.4.0.4210 is the trunk RC version which still has etaschema version 4.

So, the errror message is correct, you are trying to "downgrade" the database, and it's not allowed.
As said before, please unload db using 2.4.0.4182, then load with 2.4.0.4210.

**Comment by alexanderstc** [comment]
So the problem was that i allowed experimental build 2.4.0.4182 to leak to the public.

**Comment by SenerDemiral** [comment]
I always download last version and test.
Generally there should be one version for one day.
But there are 3 version on Dec 14, 2017. (Develop)
I did not notice installation make downgrade.

**Comment by alexanderstc** [comment]
> I did not notice installation make downgrade.

You have no way of knowing that.
That version was published by mistake, we'll try our best to avoid that in the future.

**Comment by SenerDemiral** [comment]
Never mind, I try to help you as much as I can.

**Comment by alexanderstc** [comment]
Your early tests of our builds are greatly appreciated.

**Comment by SenerDemiral** [comment]
Sure I will do.
