### ISSUE TITLE
Error when passing null value for OFFSETKEY

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#365]
In the [documentation article](https://docs.starcounter.io/v/2.4/guides/sql/offset-key#how-to-create-queries-with-offsetkey) we have the following:

```
The first time the query is executed (i.e. for the first portion), the offset key value should always be set to null or omitted.
```

I have a simple app for testing this:

```cs
using System.Linq;
using Starcounter;

namespace NullOffsetKeyIssue
{
    [Database]
    public class C1
    {
        public string Name { get; set; }
        public int Value { get; set; }
    }

    class Program
    {
        static void Main()
        {
            Handle.GET("/populate", () =>
            {
                Db.Transact(() =>
                {
                    for (int i = 0; i < 15; i++)
                    {
                        new C1
                        {
                            Name = "Item " + (i + 1),
                            Value = 5 + i * 10
                        };
                    }
                });
                return "populated 15";
            });

            // crashes
            Handle.GET("/select-offsetkey-null", () =>
            {
                var data = Db.SQL<C1>($"SELECT c FROM {typeof(C1)} c FETCH ? OFFSETKEY ?", 5, null).ToList();
                return data.Count.ToString();
            });

            // works well
            Handle.GET("/select-offsetkey-omitted", () =>
            {
                var data = Db.SQL<C1>($"SELECT c FROM {typeof(C1)} c FETCH ?", 5).ToList();
                return data.Count.ToString();
            });

            // crashes
            Handle.GET("/get-offsetkey-null", () =>
            {
                byte[] offsetKey = null;
                using (IRowEnumerator<C1> rows = (IRowEnumerator<C1>)Db.SQL<C1>($"SELECT c FROM {typeof(C1)} c FETCH ? OFFSETKEY ?", 5, offsetKey).GetEnumerator())
                {
                    while (rows.MoveNext())
                    { }
                    offsetKey = rows.GetOffsetKey();
                }
                return offsetKey?.Length.ToString();
            });
        }
    }
}
```

I'm getting the following error:

```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Starcounter.Query.Execution.FullTableScan.CreateEnumeratorWithoutNativeFilter() in C:\TeamCity\BuildAgent\work\sc-13661\Level1\src\Starcounter.QueryProcessor\Query\Execution\Enumerators\FullTableScan.cs:line 373
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-13661\Level1\src\Starcounter.QueryProcessor\Query\Execution\Enumerators\FullTableScan.cs:line 414
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NullOffsetKeyIssue.Program.<>c.<Main>b__0_1() in c:\users\untone\documents\visual studio 2017\Projects\NullOffsetKeyIssue\NullOffsetKeyIssue\Program.cs:line 36
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-13661\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 202
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-13661\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-13661\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 349
HResult=-2146233079
```

-----

Currently I checked it only in SC 2.4.0.4671. I will update the issue with testing results in v2.3.

**Comment by k-rus** [comment]
Either it is a regression or it is incorrect documentation. There are many tests of offset key in `QueryProcessingTest` in Level1 and all of them assumes that the key is not null. So it feels like it is a problem with documentation.

**Comment by Mackiovello** [comment]
The documentation for this is old and hasn't been touched in a long time. I'll investigate and see if I can clarify the documentation and make it accurate.

**Comment by Mackiovello** [comment]
`OFFSETKEY` is deprecated so this is no longer valid. Closing
