### ISSUE TITLE
Starpack exception: The tools version "12.0" is unrecognized

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#378]
SC version: 2.4.0.4963 and higher.

Currently, when I try to pack one of my repositories with starpack, I'm getting exception like this:

```
c:\www\Starcounter\StarcounterClientFiles\src\StarcounterClientFiles>starpack -p
Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "12.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  c:\www\Starcounter\StarcounterClientFiles\src\StarcounterClientFiles\StarcounterClientFiles.csproj
  at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
  at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object arg0, Object arg1)
  at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
  at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
  at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
  at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
  at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
  at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
  at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
  at Starcounter.Apps.Package.Archive.Create(String file, Boolean build, String projectConfiguration, String executable, String resourceFolder) in C:\TeamCity\BuildAgent\work\sc-14455\Level1\src\Starcounter.Apps.Package\Archive.cs:line 108
  at StarPack.ArchivePack.Execute(PackOptions options) in C:\TeamCity\BuildAgent\work\sc-14455\Level1\src\Programs\StarPack\ArchivePack.cs:line 11
  at StarPack.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-14455\Level1\src\Programs\StarPack\Program.cs:line 19
```

I know that simple solution for that, is to edit csproj file and temporarly change tool version from 12.0 to one that is listed, but obviously it should be fixed so users don't have to edit csproj manually every time.

**Comment by tomalec** [comment]
Is there anything new regarding this? We spend like an hour today shuffling `msbuild` versions and installations, to figure this out again.

**Comment by ubbeK** [comment]
I currently have this problem as well.

@miyconst

**Comment by ubbeK** [comment]
@iqbalskd

**Comment by ubbeK** [comment]
Please note that the source of starpack is in level1, not the standalone git repo.

**Comment by miyconst** [comment]
Resolved in - [Update StarPack to support Project ToolsVersion higher than 4.0](https://github.com/Starcounter/level1/pull/4842).

**Comment by ubbeK** [comment]
Thanks @miyconst !
