### ISSUE TITLE
VS2017 Error List on v2.4.0.5327 (Upgraded from 2.4.0.5313)

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#387]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Starcounter.Http.GenericHttpClientCall(String method, String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, Action`1 userDelegate, Int32 receiveTimeoutSeconds) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Internal\Rest\Http.cs:line 157
   at Starcounter.Http.POST(String uri, String body, Dictionary`2 headersDictionary, Int32 receiveTimeoutSeconds) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Internal\Rest\Http.cs:line 219
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 55
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 140
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 253
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 134
   at Starcounter.Hosting.RuntimeHosts.Shared.AppSharedRuntimeHost.Run(Func`1 configProvider, Func`1 autoStartProvdier) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.Hosting\RuntimeHosts\Shared\AppSharedRuntimeHost.cs:line 19
HResult=-2146233088
---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
HResult=-2146233088
---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
HResult=-2146233079
---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
HResult=-2146232800
---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
ErrorCode=10054
NativeErrorCode=10054
HResult=-2147467259
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated. (ScErrNetworkGatewayTerminated (SCERR10021))
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Process exitcode: -1073740791
```

**Comment by SenerDemiral** [comment]
Windows Region -> Format -> Turkish selection causes this error.
Error disappeared when changed back to English.

**Comment by SenerDemiral** [comment]
Still v2.4.0.5327 not running, exits with error code SCERR10021.
