### ISSUE TITLE
Using sort on a local list containing proxy objects, crashes the application with a 500 error statuscode

### ISSUE THREAD

**Issue by Razkan** [Starcounter/Home#447]
Starcounter version: `<2.4.990.121>`.

### Issue type

- [x] Bug

### Issue description
When using `Array.prototype.sort` on a list containing proxy object with a string comparer gives an 500 internal server error

### Reproduction code snippet

```js
var list = template.model.Persons;
list.sort((p1, p2) => p1.FirstName > p2.FirstName);        
```
or directly on the json binded list
```js
template.model.Persons.sort((p1, p2) => p1.FirstName > p2.FirstName);           
```
### Exception stack trace

Palindrom
```
PalindromConnectionError: Client error
	InternalServerError
	statusCode: 500
	reason: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[2].value', line 1, position 144.
	   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
	   at Newtonsoft.Json.JsonTextReader.ReadAsString()
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
	   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__10_0(Session session, Request request) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 139
	   at lambda_method(Closure , Request , IntPtr , IntPtr )
	   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-19108\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
	   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
	   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 356
	LineNumber=1
	LinePosition=144
	Path=[2].value
	HResult=-2146233088
	
	More information about this error may be available in the server error log.
	url: http://localhost:8080/__default/E3CE7D24EFC43E5410000020
	HTTP method: PATCH

	   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
	   at Newtonsoft.Json.JsonTextReader.ReadAsString()
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
	   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__10_0(Session session, Request request) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 139
	   at lambda_method(Closure , Request , IntPtr , IntPtr )
	   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-19108\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
	   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
	   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 356
	LineNumber=1
	LinePosition=144
	Path=[2].value
	HResult=-2146233088

```

Sc log
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[2].value', line 1, position 144.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__10_0(Session session, Request request) in C:\	c_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 139
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\	c_work\sc-19108\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\	c_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\	c_work\sc-19108\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 356
LineNumber=1
LinePosition=144
Path=[2].value
HResult=-2146233088
```

**Comment by miyconst** [comment]
@Razkan I am right that you are trying to sort a view-model array from the client side? Do you have the source of the patch sent from the client to the server?

**Comment by Razkan** [comment]
@miyconst correct, the sorting is done on a view-model array from the client side.

```js
[
  {
    "op": "replace",
    "path": "/_ver#c$",
    "value": 5
  },
  {
    "op": "test",
    "path": "/_ver#s",
    "value": 0
  },
  {
    "op": "replace",
    "path": "/HelloWorld_0/Person/2",
    "value": {
      "FirstName": "John",
      "Age": 50
    }
  }
]
```

**Comment by miyconst** [comment]
@Razkan thank you for the clarification. This operation is not supported. Only primitive values can be changed from the client side.

Still, the application should not crash, rather the patch has to be rejected with a meaningful exception. @alemoi please investigate.

**Comment by warpech** [comment]
Sebastian you will need to sort a copy of the array, not the array that is observed Palindrom.

Btw have you tried `uni-data-table` with the C# helper? It supports server side sorting done easily: https://uniform.starcounter.io/UniformDocs/DataTable

**Comment by Razkan** [comment]
@warpech when you say I have to copy the array, you mean I have to make a copy of each proxy object in the array?

I have used `uni-data-table` in a pair places, however from my personal experience the table is an investment, and in the right circumstances it works excellent while in other cases such as customization you have to settle for what you get.

**Comment by warpech** [comment]
The problem with `.sort()` in JavaScript is that it sorts the array in-place (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)

Looking at the provided patch, I think it would be enough if you only make a shallow copy of the array. If you make a deep copy, Palindrom won't be able to observe mutations to the objects in the array.

In ES6, the easiest way to make a shallow copy and then sort, is to use:

```
var list = [...template.model.Persons];
list.sort((p1, p2) => p1.FirstName > p2.FirstName); 
```

Taken from: https://stackoverflow.com/questions/9592740/how-can-you-sort-an-array-without-mutating-the-original-array

**Comment by Razkan** [comment]
@warpech works like a charm!

**Comment by miyconst** [comment]
Closing as resolved.
