### ISSUE TITLE
Error in v2.4.0.7058

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#457]
Starcounter version: `<2.4.0.7058>`.

### Issue type

- [ ] Bug
- [ ] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Reproduction code snippet

```cs

```

### Exception stack trace

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'Starcounter.Blending.Codehost, Version=0.0.5.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' or one of its dependencies. The system cannot find the file specified.
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config) in C:\	c_work\sc-19811\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 253
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider) in C:\	c_work\sc-19811\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 133
   at Starcounter.Hosting.RuntimeHosts.Shared.AppSharedRuntimeHost.Run(Func`1 configProvider, Func`1 autoStartProvdier) in C:\	c_work\sc-19811\Level1\src\Starcounter.Hosting\RuntimeHosts\Shared\AppSharedRuntimeHost.cs:line 19
FileName=Starcounter.Blending.Codehost, Version=0.0.5.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf
FusionLog=WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

HResult=-2147024894


(Double-click here for additional help)			0	
```

**Comment by alemoi** [comment]
Thanks for reporting @SenerDemiral! This is now fixed and I have started a new nightly!
