### ISSUE TITLE
Upgrading 2.3 Januari,  does not contain metatable Vacuum

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#94]
Maybe not a real problem since not many people do this specific upgrade, just to inform you.

System.Exception: ScErrMetaschemaVersionMismatch (SCERR15010): The version of the metaschema in the database does not match the metaschema version in Starcounter's binary. The database cannot be started, since the metaschema does not contain metatable Vacuum.
Version: 2.3.0.6303.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR15010.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 379
   at Starcounter.SqlProcessor.SqlProcessor.PopulateRuntimeMetadata() in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 275
   at Starcounter.Hosting.StarcounterPackage.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Hosting\Starcounter.Hosting\StarcounterPackage.cs:line 43
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-4818\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 89
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR15010

**Comment by k-rus** [comment]
This is breaking change upgrade from Starcounter version without `Vacuum` table to Starcounter with it. Before it was crash (an issue exists in a private repo), now it is more meaningful error message.

**Comment by miyconst** [comment]
Archiving.
